# SPDX-FileCopyrightText: 2025 Erik Michelson <opensource@erik.michelson.eu>
#
# SPDX-License-Identifier: MIT

name: Run checks
on:
  push:

jobs:
  reuse:
    runs-on: ubuntu-latest
    container:
      image: fsfe/reuse:5.0.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Reuse
        run: reuse lint

  biome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Install dependencies
        run: npm ci
      - name: Run biome checks
        run: npm run check

  build:
    name: Build on Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x', '20.x', '22.x']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
