# SPDX-FileCopyrightText: 2024 Erik Michelson <opensource@erik.michelson.eu>
#
# SPDX-License-Identifier: MIT

name: Run checks
on:
  push:

jobs:
  reuse:
    runs-on: ubuntu-latest
    container:
      image: fsfe/reuse:3.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Reuse
        run: reuse lint

  biome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Run biome checks
        run: npm run check

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
